name:                aoc2023
version:             0.1.0.0
description:         My solutions for Advent of Code 2023
license:             BSD3
author:              Nick Chapman
maintainer:          nic@amadido.co.uk
github:              Nick-Chapman/aoc2023.git

dependencies:
- array
- base >= 4.7 && < 5
- clock
- containers
- extra
- hashable
- unordered-containers

default-extensions:
- DeriveGeneric
- DuplicateRecordFields
- GADTs
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiWayIf
- NamedFieldPuns
- NumericUnderscores
- ScopedTypeVariables

ghc-options:
- -Werror
- -Wall
- -Wno-name-shadowing
- -Wno-x-partial #head/tail

library:
  source-dirs: src

executables:
  main.exe:
    main:                app/main.hs
    dependencies:        aoc2023
