name:                aoc2023
version:             0.1.0.0
description:         My solutions for Advent of Code 2023
license:             BSD3
author:              Nick Chapman
maintainer:          nic@amadido.co.uk
github:              Nick-Chapman/aoc2023.git

dependencies:
- ansi-terminal
- array
- async
- base >= 4.7 && < 5
- bytestring
- clock
- containers
- containers
- extra
- haskeline
- hashable
- mtl
- split
- text
- time
- transformers
- unordered-containers
- word8
#- EarleyM

default-extensions:
- BangPatterns
- DeriveGeneric
- DuplicateRecordFields
- EmptyCase
- FlexibleContexts
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- LambdaCase
- MultiWayIf
- NamedFieldPuns
- NondecreasingIndentation
- NumericUnderscores
- RankNTypes
- ScopedTypeVariables
- TypeApplications
- TypeFamilies
- UndecidableInstances

ghc-options:
- -Werror
- -Wall
- -Wno-name-shadowing
- -Wno-x-partial #head/tail

library:
  source-dirs: src

executables:
  main.exe:
    main:                app/main.hs
    dependencies:        aoc2023
